### ISSUE TITLE
GitHub actions stuck on "Cleaning up orphan processes"

### ISSUE THREAD

**Issue by jonathanpeppers** [rolfbjarne/autoformat#12]
Example at: https://github.com/jonathanpeppers/inclusive-code-reviews-ml/actions/runs/8113476182/job/22176866347?pr=166

This could be a bug in GitHub actions, but the log says:
```
Terminate orphan process: pid (2202) (dotnet)
Terminate orphan process: pid (2243) (dotnet)
```

Then at the bottom, it is stuck on:
```
Cleaning up orphan processes
```

I'm seeing this also on other builds (that are doing `dotnet build`), so it appears GitHub actions doesn't like dotnet starting daemon-like processes.

Is there an env var we should set to prevent `dotnet` processes from staying alive?

**Comment by rolfbjarne** [comment]
That might be the compiler server. I'm not if there's a way to disable it.

**Comment by jonathanpeppers** [comment]
The run above took 15 minutes, and I thought it was actually stuck... Seems like a general GitHub actions bug.

So the only "nice to have" is if there is an env var to disable the compiler server. It would probably save a second or two.
