### ISSUE TITLE
Doesn't work with inline script 

### ISSUE THREAD

**Issue by rmarinho** [rolfbjarne/autoformat#8]
https://github.com/dotnet/maui/actions/runs/4077268811/jobs/7026077700

When trying to put script like: https://github.com/dotnet/maui/blob/main/.github/workflows/dotnet-autoformat-pr.yml#L17

```
dotnet format .Microsoft.Maui.sln --no-restore --exclude Templates/src/BlazorWebView/src/SharedSource/BlazorWebViewDeveloperTools.cs
```

**Comment by rolfbjarne** [comment]
@rmarinho the `v0.2` tag has been pushed to the fixed commit, so restarting any actions should work now.
